spring.application.name=orders-service
server.port=8082

# Circuit Breaker config
resilience4j.circuitbreaker.instances.validacionServicios.sliding-window-size=5
resilience4j.circuitbreaker.instances.validacionServicios.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.validacionServicios.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.validacionServicios.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.validacionServicios.automatic-transition-from-open-to-half-open-enabled=true